apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-alert-rules
  namespace: monitoring
  labels:
    app: prometheus

data:
  kubernetes-alerts.yml: |
    groups:
      - name: devops-lab-kubernetes
        interval: 15s

        rules:

          - alert: NodeExporterDown
            expr: up{instance=~".*:9100"} == 0
            for: 2m

            labels:
              severity: critical

            annotations:
              summary: "Node Exporter target is down"
              description: "Prometheus cannot scrape Node Exporter target {{ $labels.instance }}."

          - alert: DeploymentReplicasMismatch
            expr: |
              kube_deployment_spec_replicas{namespace="devops"}
              >
              kube_deployment_status_replicas_available{namespace="devops"}
            for: 2m

            labels:
              severity: warning

            annotations:
              summary: "Deployment replicas are unavailable"
              description: "Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} does not have all desired replicas available."

          - alert: PodCrashLooping
            expr: |
              max_over_time(
                kube_pod_container_status_waiting_reason{
                  namespace="devops",
                  reason="CrashLoopBackOff"
                }[5m]
              ) >= 1
            for: 2m

            labels:
              severity: critical

            annotations:
              summary: "Pod is crash looping"
              description: "Container {{ $labels.container }} in Pod {{ $labels.pod }} is in CrashLoopBackOff."

          - alert: PodRestartingFrequently
            expr: |
              increase(
                kube_pod_container_status_restarts_total{
                  namespace="devops"
                }[10m]
              ) > 2
            for: 1m

            labels:
              severity: warning

            annotations:
              summary: "Pod is restarting frequently"
              description: "Container {{ $labels.container }} in Pod {{ $labels.pod }} restarted more than twice in ten minutes."

          - alert: PersistentVolumeClaimPending
            expr: |
              kube_persistentvolumeclaim_status_phase{
                namespace="devops",
                phase="Pending"
              } == 1
            for: 5m

            labels:
              severity: warning

            annotations:
              summary: "PVC is pending"
              description: "PVC {{ $labels.persistentvolumeclaim }} has remained Pending for more than five minutes."

          - alert: NodeCPUHigh
            expr: |
              100 - (
                avg by (instance) (
                  rate(node_cpu_seconds_total{mode="idle"}[5m])
                ) * 100
              ) > 85
            for: 5m

            labels:
              severity: warning

            annotations:
              summary: "Node CPU usage is high"
              description: "Node Exporter target {{ $labels.instance }} has CPU usage above 85% for five minutes."
