apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops
  labels:
    app: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      nodeSelector:
        workload: stateful

      tolerations:
        - key: dedicated
          operator: Equal
          value: stateful
          effect: NoSchedule
          
      containers:
        - name: backend
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          env:
            - name: REDIS_HOST
              value: "redis"

            - name: REDIS_PORT
              value: "6379"

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD

          resources:
            requests:
              cpu: 100m
              memory: 64Mi

            limits:
              cpu: 250m
              memory: 128Mi

          volumeMounts:
            - name: backend-storage
              mountPath: /data

      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-storage