apiVersion: v1
kind: ConfigMap

metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    app: alertmanager

data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

      smtp_smarthost: mailhog.monitoring.svc.cluster.local:1025
      smtp_from: alertmanager@devops-lab.local
      smtp_require_tls: false

    route:
      receiver: mailhog-email

      group_by:
        - alertname
        - namespace
        - severity

      group_wait: 10s
      group_interval: 1m
      repeat_interval: 4h

    receivers:
      - name: mailhog-email

        email_configs:
          - to: devops-team@devops-lab.local
            send_resolved: true
