apiVersion: v1
kind: Service

metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9093"

spec:
  type: ClusterIP

  selector:
    app: alertmanager

  ports:
    - name: web
      protocol: TCP
      port: 9093
      targetPort: web
