apiVersion: apps/v1
kind: Deployment

metadata:
  name: kube-state-metrics
  namespace: monitoring
  labels:
    app: kube-state-metrics

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kube-state-metrics

  template:
    metadata:
      labels:
        app: kube-state-metrics

    spec:
      serviceAccountName: kube-state-metrics

      nodeSelector:
        kubernetes.io/os: linux

      containers:
        - name: kube-state-metrics
          image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.19.1
          imagePullPolicy: IfNotPresent

          ports:
            - name: metrics
              containerPort: 8080

            - name: telemetry
              containerPort: 8081

          readinessProbe:
            httpGet:
              path: /readyz
              port: telemetry
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /livez
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 200m
              memory: 256Mi
